name: allure-testng-maven

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  build:
    name: Build-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Set up latest JDK 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'

      - uses: Wandalen/wretry.action@master
        with:
          action: n-ton4/selenoid-github-action@master
          with: |
            version: 1.8.2
            args: -limit 10
            browsers: chrome;firefox
            last-versions: 1
          attempt_limit: 3
          attempt_delay: 10000

      - name: Check Selenoid has been started
        run: curl http://localhost:4444/status
        continue-on-error: false

      - name: Decrypt Google credentials-key.json
        env:
          CREDENTIALS_KEY: ${{ secrets.CREDENTIALS_KEY }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$CREDENTIALS_KEY" \
          --output src/main/resources/google/credentials-key.json src/main/resources/google/credentials-key.json.gpg

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Tests
        run: mvn clean test "-Dsurefire.suiteXmlFiles=src/test/resources/testnggithub.xml" "-Dtestng.dtd.http=true"
        continue-on-error: true
        timeout-minutes: 3

      - name: Get Allure history
        uses: actions/checkout@v2
        if: Check Selenoid has been started.outcome == 'success'
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: Check Selenoid has been started.outcome == 'success'
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: Check Selenoid has been started.outcome == 'success'
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
