name: allure-testng-maven

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  build:
    name: Build-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE }}'
          create_credentials_file: true
          export_environment_variables: true
          credentials_file_path: '/google/credentials.json'

      - name: 'Set up latest Oracle JDK 17'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - uses: actions/checkout@v1


      - name: Run Test
        env:
          GOOGLE_AUTH_JSON: '${{ secrets.GOOGLE_AUTH }}'
          DATA: '${{ secrets.DATA }}'
        if: always()
        run: sh echo $DATA > src/test/resources/datafiles/users.csv && mvn clean test "-Dsurefire.suiteXmlFiles=src/test/resources/testng.xml" "-Dtestng.dtd.http=true"
        continue-on-error: true
