name: allure-testng-maven

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:



jobs:
  build:
    name: Build-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE }}'
          create_credentials_file: true
          export_environment_variables: true
          credentials_file_path: '/google/credentials.json'

      - name: 'Set up latest Oracle JDK 17'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
        continue-on-error: false

      - name: Decrypt Google credentials.json
        env:
          CREDENTIALS_KEY: ${{ secrets.CREDENTIALS_KEY }}
        run: |
          mkdir $GITHUB_WORKSPACE/secrets
          # --batch to prevent interactive command
          # --yes to assume "yes" for questions
          gpg --quiet --batch --yes --decrypt --passphrase="CREDENTIALS_KEY" \
          --output $GITHUB_WORKSPACE/secrets/credentials.json credentials.json.gpg

      -  run: |
          gpg --quiet --batch --yes --decrypt --passphrase="CREDENTIALS_KEY" \
          --output $GITHUB_WORKSPACE/secrets/credentials-key.json credentials-key.json.gpg

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        continue-on-error: true
        with:
          step: restore

      - name: Run Tests
        run: echo '${{ secrets.DATA }}' > 'src/test/resources/datafiles/users.csv' && mvn clean test "-Dsurefire.suiteXmlFiles=src/test/resources/testng.xml" "-Dtestng.dtd.http=true"
        continue-on-error: true

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        continue-on-error: true
        with:
          step: save

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: report-result
          PUBLISH_DIR: ./allure-history
